---
title: "Testing our data wrangling"
output: pdf_document
date: "2023-04-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Libraries and Data

First, we load our libraries:

```{r}
# For data wrangling
library(tidyverse)
# For testing our map data
library(mapview)
```


Next, we read our csv files:

```{r}
# We met all as a group and worked on the code together
# Load map data
restaurantmap_full <- read_csv("data/messydata/restaurantmap.csv", show_col_types = FALSE)
# Load nutrition info
nutritioninfo <- read_csv("data/messydata/fastfood.csv", show_col_types = FALSE)%>%
  # Remove unnecessary data
  select(restaurant, item, calories, total_fat, protein, cholesterol, sodium, total_carb, sugar)
```

## Data Wrangling

Wrangling our restaurant map locations data:

```{r}
# We met all as a group and worked on the code together
# Wrangling our map data
restmap <- restaurantmap_full %>%
  # Remove unnecessary columns
  select(-c(websites, postalCode, country, categories, address, ...1)) %>%
  # Only keep the 8 restaurants that we have nutritional data
  filter(str_detect(name, regex('Mcdonald|Sonic|Taco Bell|Arby|Subway|Dairy Queen|Burger King|Chick-fil-a', ignore_case = TRUE))) %>%
  # Handle all variations of restaurant names so that all names are written the same way.
  mutate(name = case_when(str_detect(name, regex('Mcdonald', ignore_case = TRUE)) == TRUE ~ "Mcdonalds", 
                          str_detect(name, regex('Sonic', ignore_case = TRUE)) == TRUE ~ "Sonic",
                          str_detect(name, regex('Taco Bell', ignore_case = TRUE)) == TRUE ~ "Taco Bell",
                          str_detect(name, regex('Arby', ignore_case = TRUE)) == TRUE ~ "Arbys",
                          str_detect(name, regex('Subway', ignore_case = TRUE)) == TRUE ~ "Subway",
                          str_detect(name, regex('Dairy Queen', ignore_case = TRUE)) == TRUE ~ "Dairy Queen",
                          str_detect(name, regex('Burger King', ignore_case = TRUE)) == TRUE ~ "Burger King",
                          str_detect(name, regex('Chick-fil-a', ignore_case = TRUE)) == TRUE ~ "Chick Fil-A",
                          TRUE ~ "Other"))
```

Let's make sure our map data set works!

```{r, echo=FALSE}
# Wendy
# Testing map
mapview(restmap, xcol = "longitude", ycol = "latitude", crs = 4269, grid = FALSE, zcol = "name")
```
 
 Lastly, let's write our new datasets to csv files!
 
```{r}
# Exporting CSVs
write_csv(restmap, file = 'data/restmap.csv')
write_csv(nutritioninfo, file = 'data/nutritioninfo.csv')
```
 
